### ISSUE TITLE
What does this do...?

### ISSUE THREAD

**Issue by mungewell** [wildwing1970/PSVRControl#1]
Hi, looks like this could be a cool project but can you please explain what it currently does and where you want to take it.

I see that you have picked up a few other repos relating to VR, you might find this one interesting ;-)
https://github.com/SecondReality/VirtualControllerDriver

Simon

**Comment by wildwing1970** [comment]
Thank you so much. Well, the project intention is to provide an easy Api for all the sensordata. Right now i am changing the project to use worker objects for fetching and sending data! 

Currently you can send commands to the PSVR, not all of them are working.

Expect a new release within the next week, then i put some more info to the wiki. Plz share and stay tuned!

**Comment by wildwing1970** [comment]
Sorry i am still working on the tool ........... takes a little bit longer

A screenshot where this should go ...... i think then it is a little clearer

![psvrtool](https://cloud.githubusercontent.com/assets/24974226/22475325/e30d680c-e7de-11e6-8a89-f3a5bd9a31d9.png)
